[tool.black]
line-length = 100
exclude = '''
/(
  migrations
)/
'''
force-exclude = '''
  .*/__init__.py$
'''

[tool.isort]
multi_line_output = 3
line_length = 100
include_trailing_comma = true
skip_glob = ["**/__init__.py", "**/migrations/*"]